// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "github.com/adir-ch/micro-kit/calc/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	CalculateEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.CalcService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{CalculateEndpoint: MakeCalculateEndpoint(s)}
	for _, m := range mdw["Calculate"] {
		eps.CalculateEndpoint = m(eps.CalculateEndpoint)
	}
	return eps
}
