// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/adir-ch/micro-kit/sub/pkg/endpoint"
	pb "github.com/adir-ch/micro-kit/sub/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	sub grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.SubServer {
	return &grpcServer{sub: makeSubHandler(endpoints, options["Sub"])}
}
